### ISSUE TITLE
Sequence matching :(

### ISSUE THREAD

**Issue by errm** [onfido/ecr-mirror#4]
👋 Thanks for the project it's very useful.

It seems you can't use `[` or `]` in ECR tags... thus rendering the bit in the readme that says:

> You can select a range of different tags like so: 1.1[4567]* - this will match 1.14 to 1.17.

Impossible to use.

Apparently the allowable characters are `+ - = . _ : / @`

Perhaps with a bit more substitution something like `1.1_4567=+` would work, honestly though it looks horrible, so perhaps the best fix is just to remove the bit about sequence matching from the readme!

**Comment by orf** [comment]
Thanks! The limitations on tag values in ECR is infuriating and it's a real shame `[]` isn't supported :(.

Maybe we should base64 encode the glob 🤔
